### ISSUE TITLE
Add parrot-gmp metadata to plumage

### ISSUE THREAD

**Issue by leto** [bubaflub/parrot-gmp#15]
Copy one of the already existing JSON files here:

https://github.com/parrot/plumage/tree/master/plumage/metadata

and tweak.

**Comment by bubaflub** [comment]
Distutils stuff was added in 6e66cb7.

**Comment by bubaflub** [comment]
Plumage specific stuff was added in d70790e66dd42a68

**Comment by bubaflub** [comment]
https://github.com/parrot/plumage/commit/8b41cf3934 contains my info on plumage.
