### ISSUE TITLE
Determine which GMP version to support

### ISSUE THREAD

**Issue by leto** [bubaflub/parrot-gmp#3]
4.x-5.y, what is x and y?

**Comment by bubaflub** [comment]
According to gmp-discuss, 4.2 - 5.0.2 (latest).  Should be completely backwards compatible, and 5.0.2 has been declared stable.

**Comment by leto** [comment]
Awesome! This knowledge needs to be transcribed into code that detects
the GMP version and bombs out unless we are at >= 4.2.0

On Fri, May 20, 2011 at 8:54 AM, bubaflub
reply@reply.github.com
wrote:

> According to gmp-discuss, 4.2 - 5.0.2 (latest).  Should be completely backwards compatible, and 5.0.2 has been declared stable.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bubaflub/parrot-gmp/issues/3#comment_1210754

## 

Jonathan "Duke" Leto jonathan@leto.net
209.691.DUKE // http://leto.net
NOTE: Personal email is only checked twice a day at 10am/2pm PST,
please call/text for time-sensitive matters.

**Comment by bubaflub** [comment]
Commit 4871e4c has setup.winxed checking the actual GMP version; 34a68e4 has setup.winxed checking the correct version.
