### ISSUE TITLE
Make setup.pir work

### ISSUE THREAD

**Issue by leto** [bubaflub/parrot-gmp#5]
:)

**Comment by bubaflub** [comment]
This should include some of the bootstrapping steps - like going from gmp.h -> NCI def and NCI def -> PIR via scripts.

**Comment by leto** [comment]
You probably want to make going from gmp.h -> NCI def -> PIR an
optional developer step, since some people may not have GMP headers
installed.

On Sat, May 28, 2011 at 7:20 PM, bubaflub
reply@reply.github.com
wrote:

> This should include some of the bootstrapping steps - like going from gmp.h -> NCI def and NCI def -> PIR via scripts.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bubaflub/parrot-gmp/issues/5#comment_1255795

## 

Jonathan "Duke" Leto jonathan@leto.net
209.691.DUKE // http://leto.net
NOTE: Personal email is only checked twice a day at 10am/2pm PST,
please call/text for time-sensitive matters.

**Comment by bubaflub** [comment]
Agreed - it'll be optional and the resultant files (but not the compiled files) will be committed into the repo for everyone to use.  Same with the output of the Winxed files.

**Comment by bubaflub** [comment]
With 400c07f this is complete.
