### ISSUE TITLE
Test suite coverage

### ISSUE THREAD

**Issue by bubaflub** [bubaflub/parrot-gmp#8]
Originally I wanted to auto-populate the test suite from Math::GMPz or even GMP's own C tests.  This isn't really possible - instead I'll follow them for inspiration but write my own by hand.

**Comment by leto** [comment]
Might want to see if the original gmp test suite in C is easier to parse.
On May 28, 2011 7:18 PM, "bubaflub" <
reply@reply.github.com>
wrote:

**Comment by bubaflub** [comment]
This has begun in 0204a8ef442ffce

**Comment by bubaflub** [comment]
Testing revealed a bug - I was passing the Winxed object instead of the wrapped pointer into the NCI functions which caused all kinds of nastiness.  5c6ee5eac1aa7bebaea757 fixes this and all (but the one mentioned in Issue #17) now pass.  Most of the division functions and the number theory functions remain.

**Comment by bubaflub** [comment]
Issue #17 has been fixed and with commit a97ead07d2712e5 all that remains is the random functions.  Issue #18 is a prerequisite for the random functions.

**Comment by bubaflub** [comment]
The random integer functions are covered in 9768be3 and completes test coverage of all functions.
